apiVersion: v1
kind: Service
metadata:
  name: qa-metrics-frontend
  namespace: qa-metrics
spec:
  type: ClusterIP
  selector:
    app: qa-metrics-frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
