apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qa-metrics-ingress
  namespace: qa-metrics
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: qa-metrics.internal
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: qa-metrics-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qa-metrics-frontend
                port:
                  number: 3000
